### PR TITLE
Create Temperature_prob

### PR DESCRIPTION
**Pull request by AnuskaKuila7811**
solution of Temperature_prob

### CODE REVIEW

**Comment by AnuskaKuila7811** [comment]
pls merge it

**Comment by Ayu-hack** [comment]
Please share the screenshot of working, to get it merged.

**Comment by AnuskaKuila7811** [comment]
Screenshot (93)

**Comment by AnuskaKuila7811** [comment]
I have done

**Comment by Ayu-hack** [comment]
you have mentioned it is temperature program right? Please explain the project.

**Comment by Ayu-hack** [comment]
Because cant temperature in output window. It shows something irrelevant.

**Comment by Ayu-hack** [comment]
Take your time and please fix, for sure I will merge it.

**Comment by AnuskaKuila7811** [comment]
i update this code

**Comment by Ayu-hack** [comment]
Okay. Update AS SOON AS POSSIBLE.

**Comment by AnuskaKuila7811** [comment]
i already update please check this

**Comment by Ayu-hack** [comment]
Please share the screenshot of working, to get it merged.

**Comment by AnuskaKuila7811** [comment]
Screenshot (94)

**Comment by AnuskaKuila7811** [comment]
is it correct now

**Comment by Ayu-hack** [comment]
Great Work!
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo: https://github.com/Ayu-hack/Hacktoberfest2024
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Pull request merged**
