### PR TITLE
Add solution for finding single non-duplicate element using binary search

### PR DESCRIPTION
**Pull request by SaurabhKumar171**
### Problem:
- Added a solution for finding the single non-duplicate element in a sorted array where every other element appears twice.
- Solved in O(log n) time complexity using binary search.

### Changes:
- Added Java implementation for solving the problem.

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working, to get it merged.

**Comment by SaurabhKumar171** [comment]
Please find below the screenshot of the ouput
Screenshot 2024-10-06 at 2 55 36 PM

**Comment by Ayu-hack** [comment]
Great Work ! 
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by SaurabhKumar171** [comment]
Thanks for merging the PRs! Excited for more contributions during Hacktoberfest 2024. I’ll follow you on GitHub and connect on LinkedIn. Will tag you when I post about the badges and certificate! 😄

**Pull request merged**
