### PR TITLE
Create Travelling_Salesman_Problem_readme.md

### PR DESCRIPTION
**Pull request by Vidhi-bhutia**
Readme file for previous TSP code

### CODE REVIEW

**Comment by Ayu-hack** [comment]
You needed to add readme in same PR and same folder.

**Comment by Ayu-hack** [comment]
In same folder add both the files readme and main file.

**Comment by Vidhi-bhutia** [comment]
I can't create a folder in the repository it's disabled

**Comment by Ayu-hack** [comment]
no it is not many people have done it

**Comment by Ayu-hack** [comment]
no worries. I will merged it.

**Pull request closed without merging**
