### PR TITLE
#Add Code Of Conduct

### LINKED ISSUE #48: Add Code of Conduct
I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add hacktoberfest labels.

### PR DESCRIPTION
**Pull request by ghost**
Closes #48

This PR has been raised to add a code of conduct markdown file that caters to the users of Ayu-Hack's hacktoberfest contribution repository. The file has been created and modified based on standard templates used by world wide organisations. 

Please review the PR and action accordingly. Thank you!

### CODE REVIEW

**Comment by KiranBaliga** [comment]
closes #47 

A new commit has been pushed to address the addition of greetings bot.

**Comment by Ayu-hack** [comment]
There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

Do follow my GitHub and connect with me on Linkedin
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by KiranBaliga** [comment]
@Ayu-hack I will. Thank you!

**Comment by KiranBaliga** [comment]
@Ayu-hack the issue got closed without merging 😵‍💫🥲

**Comment by Ayu-hack** [comment]
Reopened brother!

**Comment by KiranBaliga** [comment]
@Ayu-hack Thank you. Please merge and close it. Thanks again 🥲

**Comment by Ayu-hack** [comment]
Merged. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on LinkedIn
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Pull request merged**
