### PR TITLE
solution Jarvis game

### PR DESCRIPTION
**Pull request by AnuskaKuila7811**

### CODE REVIEW

**Comment by AnuskaKuila7811** [comment]
merge it

**Comment by Ayu-hack** [comment]
Please share the screenshot or video of working

**Comment by AnuskaKuila7811** [comment]
> Please share the screenshot or video of working

where i share

**Comment by AnuskaKuila7811** [comment]
why i have been blocked i can't understand

**Comment by Ayu-hack** [comment]
You aren't blocked. Attach the screenshot here in comment section

**Comment by Ayu-hack** [comment]
Use attach files option

**Comment by AnuskaKuila7811** [comment]
Screenshot (92)

**Comment by AnuskaKuila7811** [comment]
I have done

**Comment by Ayu-hack** [comment]
Great Work!
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

**Comment by Ayu-hack** [comment]
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
You should contribute to more repos. Your contribution will be accepted for sure

**Pull request merged**
