### PR TITLE
Create solution for FizzBuzz problem with basic implementation

### PR DESCRIPTION
**Pull request by SaurabhKumar171**
**Problem:**
Added a solution for the FizzBuzz problem, which prints numbers from 1 to 100 with special handling for multiples of 3, 5, and both.

**Changes:**
Added Python implementation for solving the FizzBuzz problem with basic conditional logic. The solution outputs "Fizz" for multiples of 3, "Buzz" for multiples of 5, and "FizzBuzz" for multiples of both.

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working, to get it merged. 
⭐ Star this repos to get your PR merged faster! 🚀

**Comment by SaurabhKumar171** [comment]
Hi @Ayu-hack , Pls find below the screenshot of working code.
Screenshot 2024-10-07 at 11 18 03 AM

**Comment by Ayu-hack** [comment]
## Please consider contributing to this repo: https://github.com/Ayu-hack/Hacktoberfest2024
**Sorry for the inconvenience, and thank you for your understanding! 🙏**

**Comment by SaurabhKumar171** [comment]
sure, np!

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Pull request merged**
