### PR TITLE
Create QRCode-Generator.py

### PR DESCRIPTION
**Pull request by sumedhx**
A Small contribution. 
#Hacktoberfest2024

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please share the screenshot of working, to get it merged.

**Comment by sumedhx** [comment]
> Please share the screenshot of working, to get it merged.

Screenshot 2024-10-06 at 9 09 08 PM

Below is the generated QR - 
hello

**Comment by Ayu-hack** [comment]
⭐ Star this repos to get your PR merged faster! 🚀

**Comment by Ayu-hack** [comment]
🎉 Great Work!
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me** in your Hacktoberfest certificate or badges LinkedIn post! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by sumedhx** [comment]
I am working on my python skills by making small useful projects. May i should add then to your repo or i can only merge 1 project because of it is a beginner repo for Hacktoberfest 2024

**Pull request merged**
