### PR TITLE
Create Advance Tic-Tac-Toe.py

### PR DESCRIPTION
**Pull request by Vidhi-bhutia**
Enjoy your game in 2 modes - 

1. Play with Human
2. Play with Computer

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please the share video or screenshot of working project.
It will be merged once the video or screenshot is shared.
You should contribute to more repos and PR will be accepted.
Check my [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02) here you find a post which contains all links and if possible please the repost it or share with your friends.
Thank you.

**Comment by Vidhi-bhutia** [comment]
image
image
image
image

**Comment by Ayu-hack** [comment]
Please add readme file.

**Comment by Ayu-hack** [comment]
Good project.
Merged.
More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Pull request merged**
