### PR TITLE
Pull request raised for Issue #78

### PR DESCRIPTION
**Pull request by Spardha-hash**
Hi @Ayu-hack , I have added the code for the raised issue #78 and this code is working fine. Please find the below screenshot.
stream api question
Please merge this PR.

### CODE REVIEW

**Comment by Spardha-hash** [comment]
Hi @Ayu-hack , I have created the new branch hacktoberfest and have raised the PR through this branch as in previous branch (spardha), it was showing some conflicts for me.

**Comment by Ayu-hack** [comment]
What is the name of project and what does it do? Please describe it.

**Comment by Spardha-hash** [comment]
Hi @Ayu-hack , Please find below the use case and the explanation of code.
Use Case : 
Suppose you are having a lists of objects where there are atleast 10 properties(there can be more number of properties at the industry level project) (here I have taken only 3 properties - id, tagName, tagId) and you want to perform the operations only on 2 fields using map, then by using stream functions we can do that. Additionally, it is also storing the duplicate keys (as note4 is also storing the values as 66 and 44). If you will be use the reversed() function then you will get the below output.
ss


what this code is doing?
1. Convert to Stream: noteLst.stream()
Purpose : The List is converted to a stream using stream(), allowing us to perform a series of operations on the elements of the list, such as sorting and collecting.

2. Sorting by Tag ID in Descending Order: .sorted(Comparator.comparingLong(Notes::getTagId).reversed())
Purpose: The sorted() method sorts the list based on the tagId of each Notes object. The comparator (Comparator.comparingLong(Notes::getTagId)) is used to compare the tagId values, and .reversed() ensures the sort is in descending order.

Outcome: After sorting, the Notes with the highest tagId will appear first.

Example Sorted Order:
Notes(5, "note5", 55)
Notes(4, "note4", 44)
Notes(3, "note3", 33)
Notes(2, "note2", 22)
Notes(1, "note1", 11)
Notes(6, "note4", 66) // This will come after "note4" with tagId 44

3. Collecting the Stream into a Map: .collect(Collectors.toMap(Notes::getTagName, Notes::getTagId,
                          (oldValue, newValue) -> oldValue, 
                          LinkedHashMap::new));
Purpose: The collect() method is used to accumulate the results of the stream operations into a Map.

Mapping Logic:

Notes::getTagName: The tagName property of each Notes object will be used as the key in the map.
Notes::getTagId: The tagId property will be used as the value in the map.
Handling Duplicate Keys:

When there are duplicate tagName values (as in the case of "note4"), the code resolves the conflict by specifying:
(oldValue, newValue) -> oldValue)
This means that for a duplicate key (same tagName), the old value is retained, and the new value is discarded. In this case, since "note4" appears twice, only the first occurrence (with tagId=44) will be stored in the map, and the second occurrence (with tagId=66) will be ignored.
LinkedHashMap: The LinkedHashMap::new ensures that the map maintains the insertion order. So, the elements will appear in the map in the same order as they appear in the sorted list.

**Comment by Ayu-hack** [comment]
- Great Work!
- Ask your friends to participate and share these repos. 

Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
Please readme file or instructions file with project.

**Comment by Spardha-hash** [comment]
Hi @Ayu-hack , It is not a project. It is just the problem statement like other problem statements to convert the list of objects into map by using stream functions.
Also, please let me know how can I add the readme file? Should I have to raise the separate PR for it to add the readme file?
It will be helpful for me if you will be able to let me know that how can add I readme file meanwhile please merge this PR.

**Comment by Spardha-hash** [comment]
Hi @Ayu-hack , Please let me know if any changes need to be required. I have added the readme file in this PR. Please do not mark it as invalid.

**Comment by Ayu-hack** [comment]
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Pull request merged**
