### PR TITLE
Added Hostel Accomodation System which helps college students to reserve a room in the college and written in CPP

### PR DESCRIPTION
**Pull request by LeViiAcKerMan01**
Screenshot 2024-10-07 125608

The project is working and there is no issue with thisone...

### CODE REVIEW

**Comment by LeViiAcKerMan01** [comment]
Hey @Ayu-hack , I guess thisone has also been reported by someone, as it shows excluded in thisone aswell!!

**Comment by Ayu-hack** [comment]
Yes Both the repos were reported falsely. 
Please consider contributing to this repo: https://github.com/Ayu-hack/Hacktoberfest2024
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Comment by Ayu-hack** [comment]
## Please consider contributing to this repo: https://github.com/Ayu-hack/Hacktoberfest2024
**Sorry for the inconvenience, and thank you for your understanding! 🙏**

**Comment by LeViiAcKerMan01** [comment]
Why are the repos getting excluded...
Is it because peoples are contributing DSA related stuff or some other reasons...

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Pull request merged**
