### PR TITLE
Add: Word Counter GUI Application (Issue: #73)

### LINKED ISSUE #73: Want to add a Word Counter GUI application
Word Counter GUI Application in Java
This engaging Java GUI application, named "Word Counter☆," is a user-friendly tool designed to count words and characters in a given text. The GUI is not just functional but also visually appealing, featuring a sleek design with a touch of vibrant colors. 🌈

Features 
Attractive Design :
The GUI boasts a modern design with a primary color scheme that is easy on the eyes. The subtle blend of blues and purples creates a pleasant ambiance, enhancing the user's overall experience.

Interactive Components :
The application includes various interactive components strategically placed for user convenience. These components include a logo, a title label, a text area for input, and buttons for counting and clearing.

User-Friendly Interface :
The interface is thoughtfully designed to be user-friendly. The layout is well-organized, ensuring that users can intuitively navigate through the application without any confusion.

Counting Functionality :
The "Count" button triggers the backend functionality, implemented in the CountWords class. This class utilizes a JTextArea to capture user input, counts the number of words and characters, and then displays the results in dedicated text fields.

Clearing Functionality :
To provide a seamless experience, the application includes a "Clear" button. Clicking this button invokes the clearing method from the CountWords class, ensuring a quick reset of the text area and result fields.

Dynamic Display :
The application dynamically displays the total number of words and characters in designated text boxes. The use of vibrant colors for text ensures that the results stand out against the background.

How It Works :
Input Text: Users can input their text in the spacious text area provided.
Count Button: Clicking the "Count" button triggers the word and character-counting process.
Clear Button: The "Clear" button swiftly resets the input area and result fields, providing a clean slate for the next input. 🔄

@Ayu-hack  @ayu-hack02  Can you please assign me this issue under Hacktoberfest 2024?

### PR DESCRIPTION
**Pull request by solanki03**
### Add Word Counter GUI Application (Closes #73)

This pull request addresses issue #73 by introducing a **Word Counter** GUI application that allows users to count words and characters in a given text with a sleek and intuitive design.

#### Approach:
- Designed the application with an attractive and minimal interface, focusing on user experience.
- Implemented the backend logic for counting words and characters in the `CountWords` class, keeping the structure modular and clean.
- Added interactive elements like input text area, count, clear buttons, and result fields for displaying word and character counts.
- Ensured the layout remained consistent across screens by preventing window resizing.
- Integrated clear functionality to reset the input and output fields easily.
- A jar file of this application is created to be directly used without compiling the code.

#### Linked Issue:
This PR resolves issue #73.

Please go through the implementation. Any feedback or suggestions for improvement are welcome.

####The Final Output is given below - 
image

### CODE REVIEW

**Comment by Ayu-hack** [comment]
- Please share working of video of this project to get it merged.
- It seems to be an screenshot from google or YouTube. 

More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
This PR will be closed due to no response and lack of proper information. Even it seems to be copied from google or some source. You may get banned from hacktoberfest. Please respond, last call.

**Comment by solanki03** [comment]
> This PR will be closed due to no response and lack of proper information. Even it seems to be copied from Google or some source. You may get banned from hacktoberfest. Please respond, last call.

@Ayu-hack Hello! I apologize for my delayed response. I want to clarify that this project is entirely original and not a copy of any Google projects. I created it myself. Here's a video showcasing the project. If you have any changes in mind, please let me know.

video: 

https://github.com/user-attachments/assets/62752dcb-31ac-40f7-9bab-259f4df39a40

**Comment by Ayu-hack** [comment]
Great Work ! 
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Pull request merged**
